version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

  memgraph:
    image: memgraph/memgraph-platform
    container_name: memgraph
    ports:
      - "7687:7687" #Data base port
      - "7444:7444" #Bolt port
      - "3000:3000" #Memgraph Lab port
